#ifndef HARDWARE_H
#define HARDWARE_H

#include <QApplication>
#include <QVector>
#include "config.h"

// Copied from hardware.h
#define NUMBER_OF_SWITCHES 16 // Number of foot switches
#define NUMBER_OF_EXTERNAL_SWITCHES 8

// MIDI PORTS OF VCONTROLLER
#define VC_NUMBER_OF_MIDI_PORTS 4

#define VC_PORT1_NAME "USB MIDI"
#define VC_PORT1_TYPE USBMIDI_PORT

#define VC_PORT2_NAME "MIDI 1"
#define VC_PORT2_TYPE MIDI1_PORT

#define VC_PORT3_NAME "MIDI 2"
#define VC_PORT3_TYPE MIDI2_PORT

#define VC_PORT4_NAME "INT RPI MIDI"
#define VC_PORT4_TYPE MIDI3_PORT

#define VC_PORT5_NAME "ALL MIDI"
#define VC_PORT5_TYPE ALL_MIDI_PORTS

#define VC_PORT6_NAME ""
#define VC_PORT6_TYPE USBMIDI_PORT

#define VC_PORT7_NAME ""
#define VC_PORT7_TYPE USBMIDI_PORT

#define VC_PORT8_NAME ""
#define VC_PORT8_TYPE USBMIDI_PORT

#define VC_PORT9_NAME ""
#define VC_PORT9_TYPE USBMIDI_PORT

// MIDI PORTS OF VCMINI
#define VCMINI_NUMBER_OF_MIDI_PORTS 4

#define VCMINI_PORT1_NAME "USB MIDI"
#define VCMINI_PORT1_TYPE USBMIDI_PORT

#define VCMINI_PORT2_NAME "USB MIDI HOST"
#define VCMINI_PORT2_TYPE USBHMIDI_PORT

#define VCMINI_PORT3_NAME "MIDI 1"
#define VCMINI_PORT3_TYPE MIDI1_PORT

#define VCMINI_PORT4_NAME "MIDI 2"
#define VCMINI_PORT4_TYPE MIDI2_PORT

#define VCMINI_PORT5_NAME "ALL MIDI"
#define VCMINI_PORT5_TYPE ALL_MIDI_PORTS
#define VCMINI_PORT6_NAME ""
#define VCMINI_PORT6_TYPE USBMIDI_PORT

#define VCMINI_PORT7_NAME ""
#define VCMINI_PORT7_TYPE USBMIDI_PORT

#define VCMINI_PORT8_NAME ""
#define VCMINI_PORT8_TYPE USBMIDI_PORT

#define VCMINI_PORT9_NAME ""
#define VCMINI_PORT9_TYPE USBMIDI_PORT

// MIDI PORTS OF VCTOUCH
#define VCTOUCH_NUMBER_OF_MIDI_PORTS 7

#define VCTOUCH_PORT1_NAME "USB MIDI"
#define VCTOUCH_PORT1_TYPE USBMIDI_PORT

#define VCTOUCH_PORT2_NAME "USB MIDI HOST"
#define VCTOUCH_PORT2_TYPE USBHMIDI_PORT

#define VCTOUCH_PORT3_NAME "MIDI 1"
#define VCTOUCH_PORT3_TYPE MIDI1_PORT

#define VCTOUCH_PORT4_NAME "MIDI 2"
#define VCTOUCH_PORT4_TYPE MIDI2_PORT

#define VCTOUCH_PORT5_NAME "MIDI 3"
#define VCTOUCH_PORT5_TYPE MIDI3_PORT

#define VCTOUCH_PORT6_NAME "MIDI 4"
#define VCTOUCH_PORT6_TYPE MIDI4_PORT

#define VCTOUCH_PORT7_NAME "WIRELESS MIDI"
#define VCTOUCH_PORT7_TYPE MIDI5_PORT

#define VCTOUCH_PORT8_NAME "ALL MIDI"
#define VCTOUCH_PORT8_TYPE ALL_MIDI_PORTS

#define VCTOUCH_PORT9_NAME ""
#define VCTOUCH_PORT9_TYPE USBMIDI_PORT

#define MIDI_PORT_NAMES "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9"

#endif // HARDWARE_H
